import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse(`{"title":"Tableau Public Viz of the Day","description":"There is no shortage of sites and twitter accounts that point to a new visualization every day, some even more often than that. So why start another one? Tableau's Viz of the Day is unique in that it draws from the wealth of Tableau Public, and all its picks are interactive visualizations with multiple, linked views.","frontmatter":{"title":"Tableau Public Viz of the Day","description":"There is no shortage of sites and twitter accounts that point to a new visualization every day, some even more often than that. So why start another one? Tableau's Viz of the Day is unique in that it draws from the wealth of Tableau Public, and all its picks are interactive visualizations with multiple, linked views.","date":"2012-05-14T20:30:00.000Z","tags":null,"featuredImage":null,"outline":false},"headers":[],"relativePath":"blog/2012/tableau-public-day.md","filePath":"blog/2012/tableau-public-day.md"}`);
const _sfc_main = { name: "blog/2012/tableau-public-day.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="tableau-public-viz-of-the-day" tabindex="-1">Tableau Public Viz of the Day <a class="header-anchor" href="#tableau-public-viz-of-the-day" aria-label="Permalink to &quot;Tableau Public Viz of the Day&quot;">​</a></h1><p>There is no shortage of sites and twitter accounts that point to a new visualization every day, some even more often than that. So why start another one? Tableau&#39;s <em>Viz of the Day</em> is unique in that it draws from the wealth of Tableau Public, and all its picks are interactive visualizations with multiple, linked views.</p><p>I know it sounds like marketing-speak, but people post a lot of amazing stuff on <a href="http://www.tableausoftware.com/public/">Tableau Public</a>, much of which is only seen by a handful of people. Many users post their creations on personal blogs or facebook, where they may only reach a few dozen of their friends – a real shame.</p><p><em><a href="http://www.tableausoftware.com/public/community/viz-of-the-day">Viz of the Day</a></em> is an attempt to show off some of that work. There are now over 50,000 workbooks on Tableau Public, many of which contain elaborate visualization views and, what is more, interactive dashboards that allow you to interact with the data directly in the browser. Have a question the dashboard doesn&#39;t answer? There is a download link where you can get the whole package and do your own work (and hopefully publish it again). A recent feature also lets you play with the view and post a link to your current settings to Twitter and Facebook without leaving the browser.</p><p>You can follow <a href="https://twitter.com/#!/Vizoftheday"><em>Viz of the Day</em> on Twitter</a> or subscribe to the feed on the <a href="http://www.tableausoftware.com/public/community/viz-of-the-day"><em>Viz of the Day</em> website</a> (there&#39;s even an option to subscribe via email if you&#39;re into that kind of thing).</p><hr><p>Disclosure: This posting blatantly promotes a service by <a title="Hello from Tableau (and Seattle)!" href="/blog/2012/hello-tableau-and-seattle">Tableau Software, where I am currently doing my sabbatical</a>. I was involved in the creation of the idea and the subsequent discussions. Sometimes, I walk over to the folks who are running Tableau Public and <em>Viz of the Day</em> just because I can.</p><p><em>Posted by <a href="/about">Robert Kosara</a> on May 14, 2012</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2012/tableau-public-day.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const tableauPublicDay = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  tableauPublicDay as default
};
