import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse(`{"title":"New Series: Watchlist","description":"Some of the most exciting work in our field is done by up-and-coming doctoral students, post-docs, and junior faculty members. In a new semi-regular series, I will highlight some of the people whose work I find particularly interesting and promising. The goal is to get their names onto people's radars earlier than this would have otherwise happened, in particular for those individuals who don't make a lot of noise about their work.","frontmatter":{"title":"New Series: Watchlist","description":"Some of the most exciting work in our field is done by up-and-coming doctoral students, post-docs, and junior faculty members. In a new semi-regular series, I will highlight some of the people whose work I find particularly interesting and promising. The goal is to get their names onto people's radars earlier than this would have otherwise happened, in particular for those individuals who don't make a lot of noise about their work.","date":"2011-11-08T22:10:19.000Z","tags":"Meta/Site News, journalism","featuredImage":null},"headers":[],"relativePath":"blog/2011/new-series.md","filePath":"blog/2011/new-series.md"}`);
const _sfc_main = { name: "blog/2011/new-series.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="new-series-watchlist" tabindex="-1">New Series: Watchlist <a class="header-anchor" href="#new-series-watchlist" aria-label="Permalink to &quot;New Series: Watchlist&quot;">​</a></h1><p>Some of the most exciting work in our field is done by up-and-coming doctoral students, post-docs, and junior faculty members. In a new semi-regular series, I will highlight some of the people whose work I find particularly interesting and promising. The goal is to get their names onto people&#39;s radars earlier than this would have otherwise happened, in particular for those individuals who don&#39;t make a lot of noise about their work.</p><h2 id="selection-criteria" tabindex="-1">Selection Criteria <a class="header-anchor" href="#selection-criteria" aria-label="Permalink to &quot;Selection Criteria&quot;">​</a></h2><p>Selection will be done in a completely opaque way by a panel of judges consisting of yours truly. I will focus on information visualization and visual analytics, though I also hope to include the odd scientific visualization person. I will explain why I picked each person, but I do not make any guarantees about the criteria being consistent or generally agreed upon.</p><p>The response to my <a href="/blog/2011/six-niche-visualization-blogs">niche visualization blogs posting</a> a while ago was quite positive, so I hope that this will also turn out to be interesting. As with some of the other things I am doing, my goal is to strengthen the visualization community and encourage some of the more interesting and riskier work.</p><p>Since I am currently serving on my college&#39;s review committee, I am keenly aware of the importance visibility in the community has. Getting specific and useful letters in support of promotion and tenure applications is much easier for people who are known in their field. It is never too early to start getting word out about your work, and perhaps I can encourage people to do more of that; not only the people I discuss, but also people who read the postings and realize that their own work is not getting the attention it deserves.</p><h2 id="frequency" tabindex="-1">Frequency <a class="header-anchor" href="#frequency" aria-label="Permalink to &quot;Frequency&quot;">​</a></h2><p>In a way, this is the opposite to my <a href="/influences">Lists of Influences series</a>, which hasn&#39;t seen any updates recently, despite my efforts. Since the Watchlist doesn&#39;t require cooperation from the individuals who are being discussed, this should be easier and quicker to write.</p><p>The plan is to write one entry per month for the next few months, and then whenever somebody&#39;s work strikes my fancy.</p><p><em>Posted by <a href="/about">Robert Kosara</a> on November 08, 2011</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2011/new-series.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const newSeries = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  newSeries as default
};
