import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse(`{"title":"EuroRVVV Call For Papers!","description":"I'm delighted to be one of the co-chairs of the workshop on reproducibility, verification, and validation in visualization (EuroRVVV – quite possibly the worst-acronymed workshop in visualization) at EuroVis. The topic this year is uncertainty, and we're looking for all kinds of contributions to this important topic.","frontmatter":{"title":"EuroRVVV Call For Papers!","description":"I'm delighted to be one of the co-chairs of the workshop on reproducibility, verification, and validation in visualization (EuroRVVV – quite possibly the worst-acronymed workshop in visualization) at EuroVis. The topic this year is uncertainty, and we're looking for all kinds of contributions to this important topic.","date":"2018-01-25T08:17:46.000Z","tags":null,"featuredImage":"https://media.eagereyes.org/wp-content/uploads/2018/01/eurorvvv-teaser.png","outline":false},"headers":[],"relativePath":"blog/2018/eurorvvv-call-for-papers.md","filePath":"blog/2018/eurorvvv-call-for-papers.md"}`);
const _sfc_main = { name: "blog/2018/eurorvvv-call-for-papers.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><p align="center"><img src="https://media.eagereyes.org/wp-content/uploads/2018/01/eurorvvv-teaser.png" width="560" height="198"></p><h1 id="eurorvvv-call-for-papers" tabindex="-1">EuroRVVV Call For Papers! <a class="header-anchor" href="#eurorvvv-call-for-papers" aria-label="Permalink to &quot;EuroRVVV Call For Papers!&quot;">​</a></h1><p>I&#39;m delighted to be one of the co-chairs of the workshop on reproducibility, verification, and validation in visualization (<a href="http://www.eurorvvv.org/">EuroRVVV</a> – quite possibly the worst-acronymed workshop in visualization) at <a href="http://eurovis.org">EuroVis</a>. The topic this year is uncertainty, and we&#39;re looking for all kinds of contributions to this important topic.</p><p>We talk a lot about uncertainty, but we&#39;re still lacking the tools to deal with many kinds of uncertainty. We&#39;re also lacking a good picture of what kinds of uncertainty we need to deal with, and what good strategies even look like (will all that information about the uncertainty in the data confuse and overload users?).</p><p>EuroRVVV spans the worlds of information and scientific visualization, as well as visual analytics. We believe and hope that the different subfields can learn from each other&#39;s approaches, including work outside of visualization in statistics and other areas.</p><p>We accept regular (4-page) research papers about new ideas and approaches, as well as position papers. The hope is to spur new ideas and discussion, not just present work that has been done. For a little context, I covered EuroRVVV a bit in <a href="/blog/2017/eurovis-2017-conference-report-part-1">last year&#39;s EuroVis report</a>.</p><p>If you have something interesting to say about how to deal with uncertainty in your data or your research, how to analyze data without ignoring uncertainty, how to present data with its uncertainties but without getting distracted by them, how to better think about uncertainty in visualization, or anything related, submit your paper to EuroRVVV!</p><p>For more details, see the <a href="http://www.eurorvvv.org/call-for-papers/">Call for Papers</a>! Submission deadline is March 5.</p><p><em>Posted by <a href="/about">Robert Kosara</a> on January 25, 2018</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2018/eurorvvv-call-for-papers.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const eurorvvvCallForPapers = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  eurorvvvCallForPapers as default
};
