import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Opining or Murmuring: Infographics vs. Visualization","description":"Commenting on a diagram  showing the flow of electricity from its production to its use (and waste), the author of the Junk Charts blog writes: As it stands, this chart murmurs but does not opine. Which is exactly what it should do.","frontmatter":{"title":"Opining or Murmuring: Infographics vs. Visualization","description":"Commenting on a diagram  showing the flow of electricity from its production to its use (and waste), the author of the Junk Charts blog writes: As it stands, this chart murmurs but does not opine. Which is exactly what it should do.","date":"2006-10-10T15:55:15.000Z","tags":"criticism","featuredImage":null,"outline":false},"headers":[],"relativePath":"blog/2006/opining-or-murmuring.md","filePath":"blog/2006/opining-or-murmuring.md"}');
const _sfc_main = { name: "blog/2006/opining-or-murmuring.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="opining-or-murmuring-infographics-vs-visualization" tabindex="-1">Opining or Murmuring: Infographics vs. Visualization <a class="header-anchor" href="#opining-or-murmuring-infographics-vs-visualization" aria-label="Permalink to &quot;Opining or Murmuring: Infographics vs. Visualization&quot;">​</a></h1><p>Commenting on a diagram showing the flow of electricity from its production to its use (and waste), the author of the Junk Charts blog writes: <a href="http://junkcharts.typepad.com/junk_charts/2006/10/graphical_equit_2.html"><em>As it stands, this chart murmurs but does not opine</em></a><em>.</em> Which is exactly what it should do.</p><p>I think he summed up the difference between informational graphics and visualization really well in this one sentence. The visualization is supposed to be unbiased, unopinionated, neutral; the viewer wants to have the information presented and draw his or her own conclusions, and not have the conclusion presented to her or him.</p><p>Information graphics (e.g., <a href="http://www.princeton.edu/~ina/infographics/index.html">these very interesting ones from Princeton</a>) are made not chiefly (or only) to inform, but usually have a clear agenda. They are made by people, and people have opinions. Infographics are much more digested and designed for a specific purpose than the cold, heartless visualizations.</p><p>A good deal of confusion about visualization seems to stem from this simple difference, and I think the posting linked above falls into the same trap. The data presented comes from the Energy and Environment Directorate (E&amp;ED) at Lawrance Livermore National Laboratory (LLNL), and thus from an official source. The people working for this agency certainly have opinions, but their communications must be as neutral as possible. They did an excellent job with this particular visualization, whose job it may be to murmur – but certainly not to opine.</p><p>I also find the murmuring more compelling, because it allows me to draw my own conclusions, rather than being hit over head with them. But there is clearly a place for both, and it is important to understand this difference in order to tease apart real visualization from other visual communication.</p><p><em>Posted by <a href="/about">Robert Kosara</a> on October 10, 2006. Filed under <a href="/section/criticism">criticism</a>.</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2006/opining-or-murmuring.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const opiningOrMurmuring = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  opiningOrMurmuring as default
};
