import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Data Stories Podcast: 2013 in Review, Outlook to 2014","description":"The Data Stories podcast starts the new year with Andy Kirk and me as guests. With the hosts, Enrico Bertini and Moritz Stefaner, we discuss the major developments of 2013 and look ahead to what 2014 has in store.","frontmatter":{"title":"Data Stories Podcast: 2013 in Review, Outlook to 2014","description":"The Data Stories podcast starts the new year with Andy Kirk and me as guests. With the hosts, Enrico Bertini and Moritz Stefaner, we discuss the major developments of 2013 and look ahead to what 2014 has in store.","date":"2014-01-26T21:12:15.000Z","tags":"Data Stories","featuredImage":"https://media.eagereyes.org/wp-content/uploads/2014/01/datastories-screencap1.jpg","outline":false},"headers":[],"relativePath":"blog/2014/data-stories-podcast-2013-in-review-outlook-to-2014.md","filePath":"blog/2014/data-stories-podcast-2013-in-review-outlook-to-2014.md"}');
const _sfc_main = { name: "blog/2014/data-stories-podcast-2013-in-review-outlook-to-2014.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="data-stories-podcast-2013-in-review-outlook-to-2014" tabindex="-1">Data Stories Podcast: 2013 in Review, Outlook to 2014 <a class="header-anchor" href="#data-stories-podcast-2013-in-review-outlook-to-2014" aria-label="Permalink to &quot;Data Stories Podcast: 2013 in Review, Outlook to 2014&quot;">​</a></h1><p>The <a href="http://datastori.es/">Data Stories podcast</a> starts the new year with <a href="http://www.visualisingdata.com">Andy Kirk</a> and me as guests. With the hosts, <a href="http://fellinlovewithdata.com">Enrico Bertini</a> and <a href="http://stefaner.eu">Moritz Stefaner</a>, we discuss the major developments of 2013 and look ahead to what 2014 has in store.</p><p align="center"><img class="aligncenter size-medium wp-image-3090" alt="Data Stories Screencap 1" src="https://media.eagereyes.org/wp-content/uploads/2014/01/datastories-screencap1-730x422.jpg" width="730" height="422"></p><p>You can <a href="http://datastori.es/ds31-year-review-w-andy-kirk-and-robert-kosara/">listen to the podcast episode</a> directly on its page, but you should really subscribe using your favorite podcast app. If you don&#39;t have one, at least subscribe to the datastori.es feed.</p><p>Andy and I are Data Stories veterans, with Andy having appeared four times now, and this being my third time (the first one was <a title="Listen To Me Dispense My Wisdom on the Data Stories Podcast!" href="/blog/2012/listen-dispense-wisdom-data-stories-podcast">a year ago</a>, and Enrico and I recorded <a href="http://datastori.es/data-stories-28-ieee-vis13-highlights-w-robert-kosara/">one episode at VIS</a>). Pros that we are, we were able to seamlessly talk over some of the glitches and lost connections. Mostly.</p><p>Many of the things we discussed are also covered in my <em><a title="The State of Information Visualization, 2014" href="/blog/2014/the-state-of-information-visualization-2014">State of Information Visualization</a></em> posting from two weeks ago. And while we were obviously discussing matters of great seriousness, there were also some lighter moments.</p><p align="center"><img class="aligncenter size-medium wp-image-3091" alt="Data Stories Screencap 2" src="https://media.eagereyes.org/wp-content/uploads/2014/01/datastories-screencap2-730x422.jpg" width="730" height="422"></p><p><em>Posted by <a href="/about">Robert Kosara</a> on January 26, 2014</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2014/data-stories-podcast-2013-in-review-outlook-to-2014.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const dataStoriesPodcast2013InReviewOutlookTo2014 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  dataStoriesPodcast2013InReviewOutlookTo2014 as default
};
