import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse(`{"title":"Ben Shneiderman's Chart Pies","description":"So turns out Ben Shneiderman is into pies! Actual pies that is, but in the form of charts. Rather than, you know, the other way around. Feast your eyes on delicious-looking chart pies!","frontmatter":{"title":"Ben Shneiderman's Chart Pies","description":"So turns out Ben Shneiderman is into pies! Actual pies that is, but in the form of charts. Rather than, you know, the other way around. Feast your eyes on delicious-looking chart pies!","date":"2016-09-15T21:00:47.000Z","tags":null,"featuredImage":"https://media.eagereyes.org/wp-content/uploads/2016/09/shneiderman-chartpies.jpg","outline":false},"headers":[],"relativePath":"blog/2016/ben-shneidermans-chart-pies.md","filePath":"blog/2016/ben-shneidermans-chart-pies.md"}`);
const _sfc_main = { name: "blog/2016/ben-shneidermans-chart-pies.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><p align="center"><img src="https://media.eagereyes.org/wp-content/uploads/2016/09/shneiderman-chartpies.jpg" width="816" height="612"></p><h1 id="ben-shneiderman-s-chart-pies" tabindex="-1">Ben Shneiderman&#39;s Chart Pies <a class="header-anchor" href="#ben-shneiderman-s-chart-pies" aria-label="Permalink to &quot;Ben Shneiderman&#39;s Chart Pies&quot;">​</a></h1><p>So turns out Ben Shneiderman is into pies! Actual pies that is, but in the form of charts. Rather than, you know, the other way around. Feast your eyes on delicious-looking chart pies!</p><p>I&#39;m <a href="http://andrewgelman.com">pulling a Gelman</a> here by just quoting Ben&#39;s email:</p><blockquote><p>I&#39;ve started a new hobby-- baking peach pies. I did a few this summer with the usual crisscross pattern but a friend thought these were too much like a traditional rectangular lattice. So I&#39;ve made him a parallel coords one (see photo) with peaches and strawberries. My next challenge is a treemap pie.</p><p>I thought you might like this as an item for Eager Eyes...I&#39;m sure you&#39;ll find something clever to say about these pies. Maybe we can inspire a VIS PIE contest.</p></blockquote><p>Who would take issue with a VIS PIE contest? What could go wrong with promoting pies at VIS?</p><p>Anyway, Ben is not the only one. Moritz Stefaner and others have turned data into food in their <a href="http://data-cuisine.net">Data Cuisine</a>. And Noeska Smit has a fun little blog called <em><a href="http://www.gamecakes.nl">GameCakes</a></em> (not really vis, and you have to scroll past the crocheted Androids, but her research is in visualization, so that counts).</p><p>Food and vision clearly go together. In one of my more ludicrous postings, I once <a href="/blog/2008/charts-and-metaphors">wondered what other foods could inspire chart types</a>.</p><p>I, for one, am looking forward to the treemap pie – delicious metaphor confusion and all.</p><p><em>Posted by <a href="/about">Robert Kosara</a> on September 15, 2016</em></p><aside class="comments"><hr><h2 id="comments" tabindex="-1">Comments <a class="header-anchor" href="#comments" aria-label="Permalink to &quot;Comments&quot;">​</a></h2><p><a href="http://www.noeskasmit.com" rel="nofollow noopener" target="_blank">Noeska Smit</a> says…</p><blockquote><p>Wow, thanks for the mention! I haven&#39;t baked a game-themed cake in a while though. Maybe I should pick it up again, change direction to medical visualization themed cakes ^^. So we&#39;ll have some baking at VIS this year?</p></blockquote><p>Katherine Peterson says…</p><blockquote><p>&quot;I once wondered what other foods could inspire chart types.&quot; Need I say, spaghetti and network maps?</p></blockquote></aside></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2016/ben-shneidermans-chart-pies.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const benShneidermansChartPies = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  benShneidermansChartPies as default
};
