import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Tapestry 2018 Program, Call for Demos","description":"The Tapestry 2018 program is complete, including the three keynotes and eight newly-added short stories. We are now looking for proposals for demos and will send out a call for PechaKucha-style talks to attendees soon, too.","frontmatter":{"title":"Tapestry 2018 Program, Call for Demos","description":"The Tapestry 2018 program is complete, including the three keynotes and eight newly-added short stories. We are now looking for proposals for demos and will send out a call for PechaKucha-style talks to attendees soon, too.","date":"2018-11-05T23:25:18.000Z","tags":"tapestry","featuredImage":"https://media.eagereyes.org/wp-content/uploads/2018/11/Tapestry_01.png","outline":false},"headers":[],"relativePath":"blog/2018/tapestry-2018-program-call-for-demos.md","filePath":"blog/2018/tapestry-2018-program-call-for-demos.md"}');
const _sfc_main = { name: "blog/2018/tapestry-2018-program-call-for-demos.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><p align="center"><img src="https://media.eagereyes.org/wp-content/uploads/2018/11/Tapestry_01.png" width="1283" height="710"></p><h1 id="tapestry-2018-program-call-for-demos" tabindex="-1">Tapestry 2018 Program, Call for Demos <a class="header-anchor" href="#tapestry-2018-program-call-for-demos" aria-label="Permalink to &quot;Tapestry 2018 Program, Call for Demos&quot;">​</a></h1><p>The Tapestry 2018 program is complete, including the three keynotes and eight newly-added short stories. We are now looking for proposals for demos and will send out a call for PechaKucha-style talks to attendees soon, too.</p><p>You can find the full program on the <a href="http://www.tapestryconference.com">Tapestry website</a>. I&#39;ve <a href="/blog/2018/tapestry-2018-details-and-keynote-speakers">mentioned the keynotes before</a> (Mona Chalabi of the Guardian, Matthew Kay of the University of Wisconsin, and Elijah Meeks of Netflix).</p><p>We&#39;re excited to also have a great selection of awesome speakers and topics:</p><ul><li>Aritra Dasgupta, <em>As you show, so shall you reap: causes and consequences of bad design in (scientific) visual communication</em></li><li>Jason Forrest, <em>The Data Visualizations of W.E.B. Du Bois</em></li><li>Kenneth Field, <em>The Cartography of Elections</em></li><li>Jonni Walker, <em>Bringing the Genome Home – Bridging the Gap between Conservation and Data Storytelling</em></li><li>Kristin Henry, <em>Storytelling with Color</em></li><li>Bill Shander, <em>WORDS &gt; VISUALS</em> </li><li>Alex Wein, <em>Charts as Utterances</em></li><li>Nadja Popovich, <em>Personalizing Climate Change</em></li></ul><p>The conference takes place November 29 and 30 at the University of Miami – so if you&#39;ve been on the fence about going, now is the time <a href="https://tapestry2018.eventbrite.com/">to register</a> and book your travel!</p><p>To submit a demo proposal, use <a href="https://goo.gl/forms/oEaspM9cltYgNkpe2">this demo submission form</a>. We&#39;re still working out logistics and aren&#39;t sure how many demos we&#39;ll be able to accommodate. We should know early next week, so get your proposal in by Friday (November 9)!</p><p><em>Posted by <a href="/about">Robert Kosara</a> on November 05, 2018</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2018/tapestry-2018-program-call-for-demos.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const tapestry2018ProgramCallForDemos = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  tapestry2018ProgramCallForDemos as default
};
