import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse(`{"title":"The TrustVis Workshop at EuroVis","description":"I'm one of the organizers of the new TrustVis Workshop at EuroVis this year. We haven't done a good publicizing its existence, so here is a reminder and a deadline extension: submit your papers on trust in visualization until April 5!","frontmatter":{"title":"The TrustVis Workshop at EuroVis","description":"I'm one of the organizers of the new TrustVis Workshop at EuroVis this year. We haven't done a good publicizing its existence, so here is a reminder and a deadline extension: submit your papers on trust in visualization until April 5!","date":"2019-03-19T21:58:19.000Z","tags":null,"featuredImage":"https://media.eagereyes.org/wp-content/uploads/2019/03/trust-lies.jpg","outline":false},"headers":[],"relativePath":"blog/2019/the-trustvis-workshop-at-eurovis.md","filePath":"blog/2019/the-trustvis-workshop-at-eurovis.md"}`);
const _sfc_main = { name: "blog/2019/the-trustvis-workshop-at-eurovis.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><p align="center"><img src="https://media.eagereyes.org/wp-content/uploads/2019/03/trust-lies.jpg" width="660" height="995"></p><h1 id="the-trustvis-workshop-at-eurovis" tabindex="-1">The TrustVis Workshop at EuroVis <a class="header-anchor" href="#the-trustvis-workshop-at-eurovis" aria-label="Permalink to &quot;The TrustVis Workshop at EuroVis&quot;">​</a></h1><p>I&#39;m one of the organizers of the new <a href="https://trustvis.org">TrustVis Workshop at EuroVis</a> this year. We haven&#39;t done a good publicizing its existence, so here is a reminder and a deadline extension: submit your papers on trust in visualization until April 5!</p><p>So it&#39;s not entirely new, you may remember the EuroVis Workshop on Replicability, Validation, and Verification in Visualization, better known under its highly euphonic acronym, EuroRVVV.</p><p>TrustVis is not just a new name but the attempt to broaden the scope and frame the workshop in a slightly more practice-oriented way (it&#39;s still plenty academic, don&#39;t worry). After all, replication, verification, and validation are all matters of trust in the end. Can we trust this method, this study, this technique, etc.? And how do we know?</p><p>This is also a question when it comes to users exploring a new tool. Does this show me my numbers correctly? Can I read and understand what it produces? What kinds of biases does it create? Do I know how to use it to properly show my data? These are all common and real hurdles in trying to adopt a new tool.</p><p>This even goes into matters of policy. For example, for a long time, doctors had to look at every single slice in a CT scan and could not base their diagnosis on 3D renderings. I don&#39;t know if that&#39;s still the case, but trust can clearly have enormous consequences.</p><p>The full call and details on how to submit are available on <a href="https://trustvis.org">the TrustVis website</a>. But the gist of it is: deadline is April 5, we&#39;re looking for short/position papers, the workshop will be held at EuroVis in Porto in early June.</p><p>My co-chairs Kai Lawonn, Lars Linsen, Noeska Smit, and I are looking forward to your submissions!</p><p><em>Posted by <a href="/about">Robert Kosara</a> on March 19, 2019</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2019/the-trustvis-workshop-at-eurovis.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const theTrustvisWorkshopAtEurovis = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  theTrustvisWorkshopAtEurovis as default
};
