import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse(`{"title":"Critiquing in Class Revisited","description":"Another semester is ending, and another class being taught using criticism as a main component is winding down. This time, I had a good mix of computer science, design, architecture, and liberal studies students. All the comments I received regarding the critiques were very positive, and the students' progress in their visualization designs reinforces those.","frontmatter":{"title":"Critiquing in Class Revisited","description":"Another semester is ending, and another class being taught using criticism as a main component is winding down. This time, I had a good mix of computer science, design, architecture, and liberal studies students. All the comments I received regarding the critiques were very positive, and the students' progress in their visualization designs reinforces those.","date":"2007-05-02T22:47:20.000Z","tags":null,"featuredImage":null,"outline":false},"headers":[],"relativePath":"blog/2007/critiquing-in-class-revisited.md","filePath":"blog/2007/critiquing-in-class-revisited.md"}`);
const _sfc_main = { name: "blog/2007/critiquing-in-class-revisited.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="critiquing-in-class-revisited" tabindex="-1">Critiquing in Class Revisited <a class="header-anchor" href="#critiquing-in-class-revisited" aria-label="Permalink to &quot;Critiquing in Class Revisited&quot;">​</a></h1><p>Another semester is ending, and another class being taught using criticism as a main component is winding down. This time, I had a good mix of computer science, design, architecture, and liberal studies students. All the comments I received regarding the critiques were very positive, and the students&#39; progress in their visualization designs reinforces those.</p><p>This class is called <em>Visual Communication in Computer Graphics and Art</em>, and the idea is to show the students a broad range of visual means of communication. Visualization is of course the main one, but I also talk about photography, painting, information graphics, aesthetics, perception, and representation.</p><p>Computer science students can do great things, as the showcase from an earlier class clearly demonstrates. But mixing in people with a better sense for visual things can only help, and certainly makes for much more interesting discussions.</p><p>In a <a href="/publications/Kosara_IV_2007.html">paper to be published soon</a>, I argue that <a href="/VisCrit/VisualizationCriticism.html">visualization criticism</a> is simply critical thinking about visualization. That also seems to be the way the students understood it, and they took the suggestions and criticisms to heart and worked on them (most of them, anyway). It certainly helped to have design and architecture students in the class that were much more used to this style of working than the computer science majors, but the latter didn&#39;t have any problems adapting to this style of working.</p><p>Criticism also helped connect the theory to practice. Some of the remarks my students and I made about some of the designs reflected topics from aesthetics and representation that we had talked about. This provides a n additional, different style of learning to the students, and creates more interconnections between the rather diverse topics of the class.</p><p>What is interesting is that some of the arts students actually went a lot further in their data analysis than their computer science colleagues. A few of the architecture students were also intrigued by the fact that you can use spatial metaphors to visualize any data, not just spaces.</p><p><em>Posted by <a href="/about">Robert Kosara</a> on May 02, 2007</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2007/critiquing-in-class-revisited.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const critiquingInClassRevisited = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  critiquingInClassRevisited as default
};
