import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse(`{"title":"New video: Gauges for Data Visualization, The NY Times Election Needle, and Circular Bar Charts","description":"Gauges aren't very popular in visualization, but they have some interesting properties. There is, of course, the infamous NY Times \\"election needle,\\" but you're probably using gauges every day without giving them too much thought. There's also an interesting connection with circular bar charts, which I think can work well when used as part-to-whole charts. I talk about all of this in my new video.","frontmatter":{"title":"New video: Gauges for Data Visualization, The NY Times Election Needle, and Circular Bar Charts","description":"Gauges aren't very popular in visualization, but they have some interesting properties. There is, of course, the infamous NY Times \\"election needle,\\" but you're probably using gauges every day without giving them too much thought. There's also an interesting connection with circular bar charts, which I think can work well when used as part-to-whole charts. I talk about all of this in my new video.","date":"2022-05-17T20:55:09.000Z","tags":"eagereyestv","featuredImage":"https://media.eagereyes.org/wp-content/uploads/2022/05/Gauges-Thumbnail-4x3-1.jpeg","outline":false},"headers":[],"relativePath":"blog/2022/new-video-gauges-for-data-visualization-the-ny-times-election-needle-and-circular-bar-charts.md","filePath":"blog/2022/new-video-gauges-for-data-visualization-the-ny-times-election-needle-and-circular-bar-charts.md"}`);
const _sfc_main = { name: "blog/2022/new-video-gauges-for-data-visualization-the-ny-times-election-needle-and-circular-bar-charts.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="new-video-gauges-for-data-visualization-the-ny-times-election-needle-and-circular-bar-charts" tabindex="-1">New video: Gauges for Data Visualization, The NY Times Election Needle, and Circular Bar Charts <a class="header-anchor" href="#new-video-gauges-for-data-visualization-the-ny-times-election-needle-and-circular-bar-charts" aria-label="Permalink to &quot;New video: Gauges for Data Visualization, The NY Times Election Needle, and Circular Bar Charts&quot;">​</a></h1><p>Gauges aren&#39;t very popular in visualization, but they have some interesting properties. There is, of course, the infamous NY Times &quot;election needle,&quot; but you&#39;re probably using gauges every day without giving them too much thought. There&#39;s also an interesting connection with circular bar charts, which I think can work well when used as part-to-whole charts. I talk about all of this in my new video.</p><p>I really started thinking about this when I realized that gauges aren&#39;t just displays of numbers, but also show you where you are on the scale. That&#39;s quite useful when you&#39;re trying to understand things like how close you are to the maximum RPM in your car, or the range of empty to full on your fuel gauge.</p><p>Circular bar charts are kind of related, and not just because they&#39;re also round shapes. I think they work well on the Apple Watch to show you how well you&#39;re doing in your daily fitness goals, and they actually seem to be fairly common to show goal completion. That makes them part-to-whole charts, though with the twist that you can go beyond 100%. Different widgets and devices show you the part beyond 100% differently, and some don&#39;t actually bother to show you how far you got beyond 100%.</p><p>All of this is in my new video, which you can watch below or <a href="https://youtu.be/ePpSYA9deKA">over on YouTube</a>. As usual, I&#39;m very curious about your thoughts! And if you like the video, please head over to YouTube to click the like button and maybe leave a comment – and subscribe to the channel, if you haven&#39;t already!</p><p align="center"><iframe width="560" height="315" src="https://www.youtube.com/embed/ePpSYA9deKA?si=_4qjdDmIe6AJ5TMf" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></p><p><em>Posted by <a href="/about">Robert Kosara</a> on May 17, 2022</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2022/new-video-gauges-for-data-visualization-the-ny-times-election-needle-and-circular-bar-charts.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const newVideoGaugesForDataVisualizationTheNyTimesElectionNeedleAndCircularBarCharts = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  newVideoGaugesForDataVisualizationTheNyTimesElectionNeedleAndCircularBarCharts as default
};
