import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse(`{"title":"Looking for Parallel Sets Users with Real Data","description":"We are looking for people who use Parallel Sets with real-world data and who would be interested in taking part in writing up a case study for the InfoVis Discovery Exhibition. You don't have to share your data, and the images can be anonymized, but it has to be real data (and you have to be able to describe what it is and what you learned in a way that is not too general).","frontmatter":{"title":"Looking for Parallel Sets Users with Real Data","description":"We are looking for people who use Parallel Sets with real-world data and who would be interested in taking part in writing up a case study for the InfoVis Discovery Exhibition. You don't have to share your data, and the images can be anonymized, but it has to be real data (and you have to be able to describe what it is and what you learned in a way that is not too general).","date":"2009-07-07T07:00:09.000Z","tags":null,"featuredImage":null,"outline":false},"headers":[],"relativePath":"blog/2009/parsets-users-with-real-data.md","filePath":"blog/2009/parsets-users-with-real-data.md"}`);
const _sfc_main = { name: "blog/2009/parsets-users-with-real-data.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="looking-for-parallel-sets-users-with-real-data" tabindex="-1">Looking for Parallel Sets Users with Real Data <a class="header-anchor" href="#looking-for-parallel-sets-users-with-real-data" aria-label="Permalink to &quot;Looking for Parallel Sets Users with Real Data&quot;">​</a></h1><p>We are looking for people who use <a href="/parallel-sets">Parallel Sets</a> with real-world data and who would be interested in taking part in writing up a case study for the InfoVis <a href="http://www.discoveryexhibition.org/">Discovery Exhibition</a>. You don&#39;t have to share your data, and the images can be anonymized, but it has to be real data (and you have to be able to describe what it is and what you learned in a way that is not too general).</p><p>What&#39;s in it for you, if you participate? You will be listed as a co-author on the submission, and you get a warm fuzzy feeling from helping the visualization world see its potential impact in the real world. At some point in the future, i will also put together a showcase of uses for Parallel Sets on this site.</p><p>If you are interested, please <a href="/contact">drop me a line</a> with a brief description (2-3 sentences) of the kind of data you&#39;re using it with, and what you have learned from its use. For the actual submission, I will need around 500 words of description plus a few screenshots. I already have one co-author and am looking for one to two more. The deadline for submission is next week, but I will be traveling and will need to hear from you by this Friday (July 10).</p><p>The next version of Parallel Sets is in the works, and I hope to get it done this week. Things are fairly busy right now with proposal writing, and I have a few bugs to fix before I can release 2.1. But it will have a few new useful features, and be able to deal better with very high-dimensional data.</p><p>In unrelated site news, comments are now moderated again. I am getting around 50 spam comments a day at the moment, so there is unfortunately no way around this. I am trying to moderate new comments quickly, but it can take some time for them to be published.</p><p><em>Posted by <a href="/about">Robert Kosara</a> on July 07, 2009</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2009/parsets-users-with-real-data.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const parsetsUsersWithRealData = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  parsetsUsersWithRealData as default
};
