import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"eagereyesTV: What Is Data? Part 2, Are Images Data?","description":"Visualization turns data into images, but are images themselves data? There are often claims that they are, but then you mostly see the images themselves without much additional data. In this video, I look at image browsers, a project classifying selfies along a number of criteria, and the additional information stored in HEIC that makes things like portrait mode and relighting possible.","frontmatter":{"title":"eagereyesTV: What Is Data? Part 2, Are Images Data?","description":"Visualization turns data into images, but are images themselves data? There are often claims that they are, but then you mostly see the images themselves without much additional data. In this video, I look at image browsers, a project classifying selfies along a number of criteria, and the additional information stored in HEIC that makes things like portrait mode and relighting possible.","date":"2019-12-16T05:01:25.000Z","tags":"eagereyestv","featuredImage":"https://media.eagereyes.org/wp-content/uploads/2019/12/4CC1DFDA-BF8A-4D11-9D4B-D2EEBAFFD15E.jpeg","outline":false},"headers":[],"relativePath":"blog/2019/eagereyestv-what-is-data-part-2-are-images-data.md","filePath":"blog/2019/eagereyestv-what-is-data-part-2-are-images-data.md"}');
const _sfc_main = { name: "blog/2019/eagereyestv-what-is-data-part-2-are-images-data.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="eagereyestv-what-is-data-part-2-are-images-data" tabindex="-1">eagereyesTV: What Is Data? Part 2, Are Images Data? <a class="header-anchor" href="#eagereyestv-what-is-data-part-2-are-images-data" aria-label="Permalink to &quot;eagereyesTV: What Is Data? Part 2, Are Images Data?&quot;">​</a></h1><p>Visualization turns data into images, but are images themselves data? There are often claims that they are, but then you mostly see the images themselves without much additional data. In this video, I look at image browsers, a project classifying selfies along a number of criteria, and the additional information stored in HEIC that makes things like portrait mode and relighting possible.</p><p>This is the second video in my <em>What is Data?</em> series, and the question that initially got me <a href="/blog/2019/eagereyestv-what-is-data-part-1-file-formats-and-intent">thinking about file formats, etc.</a></p><p>Watch the video below or <a href="https://youtu.be/xKfpBmuZkWU">head over to YouTube</a> (and while you’re there, subscribe to the channel!).</p><p align="center"><iframe width="560" height="315" src="https://www.youtube.com/embed/xKfpBmuZkWU?si=FYaj0fdqk29QX7ld" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></p><p>These are the apps and websites I use and discuss in the video:</p><ul><li><a href="https://parametric.press/issue-01/unraveling-the-jpeg/"><em>Unraveling the JPEG</em> on the Parametric Press</a></li><li><a href="https://wikiview.net">WikiView</a></li><li><a href="http://selfiecity.net">Selfie City</a></li><li><a href="https://halide.cam">Halide camera app</a></li></ul><p>As always, let me know what you think! And if you enjoy these videos, subscribe to the channel and maybe give the video a like!</p><p><em>Posted by <a href="/about">Robert Kosara</a> on December 16, 2019. Filed under <a href="/tag/eagereyestv">eagereyesTV</a>.</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2019/eagereyestv-what-is-data-part-2-are-images-data.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const eagereyestvWhatIsDataPart2AreImagesData = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  eagereyestvWhatIsDataPart2AreImagesData as default
};
