import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"A Smart Take on Election Maps","description":"When maps are used to display data, there is often a discrepancy between the data being shown, which almost never relates to area, and the area of the different parts of the map. This is particularly common in election maps. This new map of votes in the 2016 U.S. Presidential election cleverly combines geography and data in a clear and compelling way.","frontmatter":{"title":"A Smart Take on Election Maps","description":"When maps are used to display data, there is often a discrepancy between the data being shown, which almost never relates to area, and the area of the different parts of the map. This is particularly common in election maps. This new map of votes in the 2016 U.S. Presidential election cleverly combines geography and data in a clear and compelling way.","date":"2018-01-09T20:40:49.000Z","tags":null,"featuredImage":"https://media.eagereyes.org/wp-content/uploads/2018/01/2016_election_map_2x.png","outline":false},"headers":[],"relativePath":"blog/2018/a-smart-take-on-election-maps.md","filePath":"blog/2018/a-smart-take-on-election-maps.md"}');
const _sfc_main = { name: "blog/2018/a-smart-take-on-election-maps.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="a-smart-take-on-election-maps" tabindex="-1">A Smart Take on Election Maps <a class="header-anchor" href="#a-smart-take-on-election-maps" aria-label="Permalink to &quot;A Smart Take on Election Maps&quot;">​</a></h1><p>When maps are used to display data, there is often a discrepancy between the data being shown, which almost never relates to area, and the area of the different parts of the map. This is <a href="/blog/2016/all-those-misleading-election-maps">particularly common in election maps</a>. This new <a href="https://xkcd.com/1939/">map of votes in the 2016 U.S. Presidential election</a> cleverly combines geography and data in a clear and compelling way.</p><p>This map is another piece by <a href="https://xkcd.com">xkcd</a>&#39;s Randall Munroe (also author of <a href="/blog/2015/review-munroes-thing-explainer-and-pinkers-sense-of-style"><em>Thing Explainer</em></a>). It works well for a number of reasons.</p><ul><li>It doesn&#39;t distort our perception of the data by using color on area, which is determined by land surface rather than population or electoral votes.</li><li>It doesn&#39;t distort geography, like cartograms</li><li>It uses symbols of people to show a set multiple (somewhat similar to <a href="/techniques/isotype">ISOTYPE</a>)</li><li>Its hand-drawn aesthetic is fun and non-intimidating</li></ul><p>The style of this map is not entirely new. In fact, <a href="https://en.wikipedia.org/wiki/Dot_distribution_map">dot density maps</a> have a long history but have fallen out of fashion over the last few decades (a colleague of mine blames GIS for this development). Here&#39;s a nice example about agriculture – which you might imagine would be about area, but it&#39;s not (<a href="https://www.e-education.psu.edu/geog486/node/1870">from here</a>).</p><p align="center"><img class="aligncenter size-full wp-image-10394" src="https://media.eagereyes.org/wp-content/uploads/2018/01/cropland_dotdensity.png" alt="" width="700" height="455"></p><p>Using fewer but larger symbols, it&#39;s possible to make them recognizable. There&#39;s a balance though between the size and the density that can be achieved. Munroe has done a great job in his map, showing just enough density so you can find some patterns, but not making the symbols too tiny. I also think he is trying to make a point with the single figures in Wyoming and the Dakotas (also Alaska and Hawaii).</p><p align="center"><img class="aligncenter size-full wp-image-10393" src="https://media.eagereyes.org/wp-content/uploads/2018/01/2016_election_map_2x.png" alt="" width="1480" height="1124"></p><p>It&#39;s a great map, and perhaps the most effective one I&#39;ve seen showing this data so far, given the United States&#39; vast area and enormous differences in population density.</p><p><em>Posted by <a href="/about">Robert Kosara</a> on January 09, 2018</em></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("blog/2018/a-smart-take-on-election-maps.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const aSmartTakeOnElectionMaps = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  aSmartTakeOnElectionMaps as default
};
