import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Facilitating Knowledge Maintenance of Clinical Guidelines and Protocols","description":"Clinical protocols and guidelines are widely used in the medical domain to improve disease management techniques. Different software systems are in development to support the design and the execution of such guidelines. The bottleneck in the guideline software developing process is the transformation of the text-based clinical guidelines into a formal representation, which can be used by the execution software. This paper introduces a method and a tool that was designed to provide a solution for that bottleneck. The so-called Guideline Markup Tool (GMT) facilitates the translation of guidelines into a formal representation written in XML. This tool enables the protocol designer to create links between the original guideline and its formal representation and ease the editing of guidelines applying design patterns in the form of macros. The usefulness of our approach is illustrated using GMT to edit Asbru protocols. We performed a usability study with eight participants to examine the usefulness of the GMT and of the Asbru macros, which showed that the proposed approach is very appropriate to author and maintain clinical guidelines.","frontmatter":{"title":"Facilitating Knowledge Maintenance of Clinical Guidelines and Protocols","description":"Clinical protocols and guidelines are widely used in the medical domain to improve disease management techniques. Different software systems are in development to support the design and the execution of such guidelines. The bottleneck in the guideline software developing process is the transformation of the text-based clinical guidelines into a formal representation, which can be used by the execution software. This paper introduces a method and a tool that was designed to provide a solution for that bottleneck. The so-called Guideline Markup Tool (GMT) facilitates the translation of guidelines into a formal representation written in XML. This tool enables the protocol designer to create links between the original guideline and its formal representation and ease the editing of guidelines applying design patterns in the form of macros. The usefulness of our approach is illustrated using GMT to edit Asbru protocols. We performed a usability study with eight participants to examine the usefulness of the GMT and of the Asbru macros, which showed that the proposed approach is very appropriate to author and maintain clinical guidelines."},"headers":[],"relativePath":"publications/Votruba-MedInfo-2004.md","filePath":"publications/Votruba-MedInfo-2004.md"}');
const _sfc_main = { name: "publications/Votruba-MedInfo-2004.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="facilitating-knowledge-maintenance-of-clinical-guidelines-and-protocols" tabindex="-1">Facilitating Knowledge Maintenance of Clinical Guidelines and Protocols <a class="header-anchor" href="#facilitating-knowledge-maintenance-of-clinical-guidelines-and-protocols" aria-label="Permalink to &quot;Facilitating Knowledge Maintenance of Clinical Guidelines and Protocols&quot;">​</a></h1><blockquote><p><em>Clinical protocols and guidelines are widely used in the medical domain to improve disease management techniques. Different software systems are in development to support the design and the execution of such guidelines. The bottleneck in the guideline software developing process is the transformation of the text-based clinical guidelines into a formal representation, which can be used by the execution software. This paper introduces a method and a tool that was designed to provide a solution for that bottleneck. The so-called Guideline Markup Tool (GMT) facilitates the translation of guidelines into a formal representation written in XML. This tool enables the protocol designer to create links between the original guideline and its formal representation and ease the editing of guidelines applying design patterns in the form of macros. The usefulness of our approach is illustrated using GMT to edit Asbru protocols. We performed a usability study with eight participants to examine the usefulness of the GMT and of the Asbru macros, which showed that the proposed approach is very appropriate to author and maintain clinical guidelines.</em></p></blockquote><p>Peter Votruba, Silvia Miksch, and Robert Kosara, <a href="https://media.eagereyes.org/papers/2004/Votruba-MedInfo-2004.pdf" target="_blank">Facilitating Knowledge Maintenance of Clinical Guidelines and Protocols</a>, <em>11th World Congress on Medical Informatics (MedInfo)</em>, pp. 57–61, 2004.</p><div class="language-bibtex"><button title="Copy Code" class="copy"></button><span class="lang">bibtex</span><pre class="shiki material-theme-palenight"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">@</span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">inproceedings</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#FFCB6B" })}">Votruba:MedInfo:2004</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">year</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">2004</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">title</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Facilitating Knowledge Maintenance of Clinical Guidelines and Protocols</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">author</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Peter Votruba and Silvia Miksch and Robert Kosara</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">venue</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">11th World Congress on Medical Informatics (MedInfo)</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">pages</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">57–61</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">abstract</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Clinical protocols and guidelines are widely used in the medical domain to improve disease management techniques. Different software systems are in development to support the design and the execution of such guidelines. The bottleneck in the guideline software developing process is the transformation of the text-based clinical guidelines into a formal representation, which can be used by the execution software. This paper introduces a method and a tool that was designed to provide a solution for that bottleneck. The so-called Guideline Markup Tool (GMT) facilitates the translation of guidelines into a formal representation written in XML. This tool enables the protocol designer to create links between the original guideline and its formal representation and ease the editing of guidelines applying design patterns in the form of macros. The usefulness of our approach is illustrated using GMT to edit Asbru protocols. We performed a usability study with eight participants to examine the usefulness of the GMT and of the Asbru macros, which showed that the proposed approach is very appropriate to author and maintain clinical guidelines.</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("publications/Votruba-MedInfo-2004.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const VotrubaMedInfo2004 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  VotrubaMedInfo2004 as default
};
