import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Communicating Time-Oriented, Skeletal Plans to Domain Experts Lucidly","description":"Practical planning systems for real-world environments imply a striking challenge, because the planning and visualization techniques available are not that straightforwardly applicable. Skeletal plans are an effective way to reuse existing domain-specific procedural knowledge, but leave room for execution-time flexibility. However, the basic concepts of skeletal plans are not sufficient in our medical domain. First, the temporal dimensions and variability of plans have to be modelled explicitly. Second, the compositions and the interdependencies of different plans are not lucid to medical domain experts. The aim of our paper is to overcome these limitations and to present an intuitive user interface to the plan-representation language Asbru. We explored different representations and developed a powerful plan visualization, called AsbruView. AsbruView consists of two views, first, a topological view, which utilizes the metaphor graphics of “running tracks” and “traffic” and, second, a temporal view, which utilizes the idea of LifeLines.","frontmatter":{"title":"Communicating Time-Oriented, Skeletal Plans to Domain Experts Lucidly","description":"Practical planning systems for real-world environments imply a striking challenge, because the planning and visualization techniques available are not that straightforwardly applicable. Skeletal plans are an effective way to reuse existing domain-specific procedural knowledge, but leave room for execution-time flexibility. However, the basic concepts of skeletal plans are not sufficient in our medical domain. First, the temporal dimensions and variability of plans have to be modelled explicitly. Second, the compositions and the interdependencies of different plans are not lucid to medical domain experts. The aim of our paper is to overcome these limitations and to present an intuitive user interface to the plan-representation language Asbru. We explored different representations and developed a powerful plan visualization, called AsbruView. AsbruView consists of two views, first, a topological view, which utilizes the metaphor graphics of “running tracks” and “traffic” and, second, a temporal view, which utilizes the idea of LifeLines."},"headers":[],"relativePath":"publications/Miksch-DEXA-1999.md","filePath":"publications/Miksch-DEXA-1999.md"}');
const _sfc_main = { name: "publications/Miksch-DEXA-1999.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="communicating-time-oriented-skeletal-plans-to-domain-experts-lucidly" tabindex="-1">Communicating Time-Oriented, Skeletal Plans to Domain Experts Lucidly <a class="header-anchor" href="#communicating-time-oriented-skeletal-plans-to-domain-experts-lucidly" aria-label="Permalink to &quot;Communicating Time-Oriented, Skeletal Plans to Domain Experts Lucidly&quot;">​</a></h1><blockquote><p><em>Practical planning systems for real-world environments imply a striking challenge, because the planning and visualization techniques available are not that straightforwardly applicable. Skeletal plans are an effective way to reuse existing domain-specific procedural knowledge, but leave room for execution-time flexibility. However, the basic concepts of skeletal plans are not sufficient in our medical domain. First, the temporal dimensions and variability of plans have to be modelled explicitly. Second, the compositions and the interdependencies of different plans are not lucid to medical domain experts. The aim of our paper is to overcome these limitations and to present an intuitive user interface to the plan-representation language Asbru. We explored different representations and developed a powerful plan visualization, called AsbruView. AsbruView consists of two views, first, a topological view, which utilizes the metaphor graphics of “running tracks” and “traffic” and, second, a temporal view, which utilizes the idea of LifeLines.</em></p></blockquote><p>Silvia Miksch and Robert Kosara, <a href="https://media.eagereyes.org/papers/1999/Miksch-DEXA-1999.pdf" target="_blank">Communicating Time-Oriented, Skeletal Plans to Domain Experts Lucidly</a>, <em>Proceedings of the 10th International Conference on Database and Expert Systems Applications (DEXA)</em>, pp. 1041–1051, 1999.</p><div class="language-bibtex"><button title="Copy Code" class="copy"></button><span class="lang">bibtex</span><pre class="shiki material-theme-palenight has-diff"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">@</span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">inproceedings</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#FFCB6B" })}">Miksch:DEXA:1999</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">year</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">1999</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">title</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Communicating Time-Oriented, Skeletal Plans to Domain Experts Lucidly</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">author</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Silvia Miksch and Robert Kosara</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">venue</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Proceedings of the 10th International Conference on Database and Expert Systems Applications (DEXA)</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">pages</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">1041–1051</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">abstract</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Practical planning systems for real-world environments imply a striking challenge, because the planning and visualization techniques available are not that straightforwardly applicable. Skeletal plans are an effective way to reuse existing domain-specific procedural knowledge, but leave room for execution-time flexibility. However, the basic concepts of skeletal plans are not sufficient in our medical domain. First, the temporal dimensions and variability of plans have to be modelled explicitly. Second, the compositions and the interdependencies of different plans are not lucid to medical domain experts. The aim of our paper is to overcome these limitations and to present an intuitive user interface to the plan-representation language Asbru. We explored different representations and developed a powerful plan visualization, called AsbruView. AsbruView consists of two views, first, a topological view, which utilizes the metaphor graphics of “running tracks” and “traffic” and, second, a temporal view, which utilizes the idea of LifeLines.</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("publications/Miksch-DEXA-1999.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const MikschDEXA1999 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  MikschDEXA1999 as default
};
