import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Reflecting on the Design Criteria for Explanatory Visualizations","description":"The visualization field has developed a good set of design criteria, metrics, and methods to assess visualization techniques and systems. These are all focused on analytical and exploratory uses, however. A large class of visualizations are created to present and communicate data and issues, however, and are seen by millions of people. We do not currently have a good grasp of what criteria should be used to systematically design and compare them, and how to do that. The aim of this paper is to raise the issue, describe different uses of visualizations, and propose criteria that should be considered while designing and critiquing them.","frontmatter":{"title":"Reflecting on the Design Criteria for Explanatory Visualizations","description":"The visualization field has developed a good set of design criteria, metrics, and methods to assess visualization techniques and systems. These are all focused on analytical and exploratory uses, however. A large class of visualizations are created to present and communicate data and issues, however, and are seen by millions of people. We do not currently have a good grasp of what criteria should be used to systematically design and compare them, and how to do that. The aim of this paper is to raise the issue, describe different uses of visualizations, and propose criteria that should be considered while designing and critiquing them."},"headers":[],"relativePath":"publications/Kosara-C4PGV-2016.md","filePath":"publications/Kosara-C4PGV-2016.md"}');
const _sfc_main = { name: "publications/Kosara-C4PGV-2016.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="reflecting-on-the-design-criteria-for-explanatory-visualizations" tabindex="-1">Reflecting on the Design Criteria for Explanatory Visualizations <a class="header-anchor" href="#reflecting-on-the-design-criteria-for-explanatory-visualizations" aria-label="Permalink to &quot;Reflecting on the Design Criteria for Explanatory Visualizations&quot;">​</a></h1><blockquote><p><em>The visualization field has developed a good set of design criteria, metrics, and methods to assess visualization techniques and systems. These are all focused on analytical and exploratory uses, however. A large class of visualizations are created to present and communicate data and issues, however, and are seen by millions of people. We do not currently have a good grasp of what criteria should be used to systematically design and compare them, and how to do that. The aim of this paper is to raise the issue, describe different uses of visualizations, and propose criteria that should be considered while designing and critiquing them.</em></p></blockquote><p>Robert Kosara, Aritra Dasgupta, and Enrico Bertini, <a href="https://media.eagereyes.org/papers/2016/Kosara-C4PGV-2016.pdf" target="_blank">Reflecting on the Design Criteria for Explanatory Visualizations</a>, <em>Workshop on Creation, Curation, Critique and Conditioning of Principles and Guidelines in Visualization (C4PGV)</em>, 2016.</p><div class="language-bibtex"><button title="Copy Code" class="copy"></button><span class="lang">bibtex</span><pre class="shiki material-theme-palenight has-diff"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">@</span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">inproceedings</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#FFCB6B" })}">Kosara:C4PGV:2016</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">year</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">2016</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">title</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Reflecting on the Design Criteria for Explanatory Visualizations</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">author</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Robert Kosara and Aritra Dasgupta and Enrico Bertini</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">venue</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Workshop on Creation, Curation, Critique and Conditioning of Principles and Guidelines in Visualization (C4PGV)</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">abstract</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">The visualization field has developed a good set of design criteria, metrics, and methods to assess visualization techniques and systems. These are all focused on analytical and exploratory uses, however. A large class of visualizations are created to present and communicate data and issues, however, and are seen by millions of people. We do not currently have a good grasp of what criteria should be used to systematically design and compare them, and how to do that. The aim of this paper is to raise the issue, describe different uses of visualizations, and propose criteria that should be considered while designing and critiquing them.</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("publications/Kosara-C4PGV-2016.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const KosaraC4PGV2016 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  KosaraC4PGV2016 as default
};
