import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Size Judgment and Comparison in Tag Clouds","description":"Tag clouds can be used for a variety of purposes, like providing a high-level understanding of a document. It is still unclear how users perceive the size of the words in tag clouds and how they make their judgments of the size of words. In this poster, we look at how users estimate the relative sizes of words given different characteristics. We studied the influence of decorations like filled areas, boxes, and shadows to determine whether they would influence the perceived size. Another parameter we tested was the appearance of words (i.e. by choosing words with and without ascenders and descenders). We found significant effects from all of those parameters, which suggests that designers of tag clouds need to be aware of the influence of design choices on the perceived data.","frontmatter":{"title":"Size Judgment and Comparison in Tag Clouds","description":"Tag clouds can be used for a variety of purposes, like providing a high-level understanding of a document. It is still unclear how users perceive the size of the words in tag clouds and how they make their judgments of the size of words. In this poster, we look at how users estimate the relative sizes of words given different characteristics. We studied the influence of decorations like filled areas, boxes, and shadows to determine whether they would influence the perceived size. Another parameter we tested was the appearance of words (i.e. by choosing words with and without ascenders and descenders). We found significant effects from all of those parameters, which suggests that designers of tag clouds need to be aware of the influence of design choices on the perceived data."},"headers":[],"relativePath":"publications/Dhou-InfoVisPoster-2013.md","filePath":"publications/Dhou-InfoVisPoster-2013.md"}');
const _sfc_main = { name: "publications/Dhou-InfoVisPoster-2013.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="size-judgment-and-comparison-in-tag-clouds" tabindex="-1">Size Judgment and Comparison in Tag Clouds <a class="header-anchor" href="#size-judgment-and-comparison-in-tag-clouds" aria-label="Permalink to &quot;Size Judgment and Comparison in Tag Clouds&quot;">​</a></h1><blockquote><p><em>Tag clouds can be used for a variety of purposes, like providing a high-level understanding of a document. It is still unclear how users perceive the size of the words in tag clouds and how they make their judgments of the size of words. In this poster, we look at how users estimate the relative sizes of words given different characteristics. We studied the influence of decorations like filled areas, boxes, and shadows to determine whether they would influence the perceived size. Another parameter we tested was the appearance of words (i.e. by choosing words with and without ascenders and descenders). We found significant effects from all of those parameters, which suggests that designers of tag clouds need to be aware of the influence of design choices on the perceived data.</em></p></blockquote><p>Khaldoon (Kal) Dhou, Robert Kosara, Mirsad Hadzikadic, and Mark Faust, <a href="https://media.eagereyes.org/papers/2013/Dhou-InfoVisPoster-2013.pdf" target="_blank">Size Judgment and Comparison in Tag Clouds</a>, <em>IEEE Information Visualization Posters</em>, 2013.</p><div class="language-bibtex"><button title="Copy Code" class="copy"></button><span class="lang">bibtex</span><pre class="shiki material-theme-palenight has-diff"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">@</span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">inproceedings</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#FFCB6B" })}">Dhou:InfoVisPoster:2013</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">year</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">2013</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">title</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Size Judgment and Comparison in Tag Clouds</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">author</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Khaldoon (Kal) Dhou and Robert Kosara and Mirsad Hadzikadic and Mark Faust</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">venue</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">IEEE Information Visualization Posters</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">abstract</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Tag clouds can be used for a variety of purposes, like providing a high-level understanding of a document. It is still unclear how users perceive the size of the words in tag clouds and how they make their judgments of the size of words. In this poster, we look at how users estimate the relative sizes of words given different characteristics. We studied the influence of decorations like filled areas, boxes, and shadows to determine whether they would influence the perceived size. Another parameter we tested was the appearance of words (i.e. by choosing words with and without ascenders and descenders). We found significant effects from all of those parameters, which suggests that designers of tag clouds need to be aware of the influence of design choices on the perceived data.</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("publications/Dhou-InfoVisPoster-2013.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const DhouInfoVisPoster2013 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  DhouInfoVisPoster2013 as default
};
