import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Visualization Criticism","description":"Criticism is a vital part of the practice of design, architecture, and art, and as such is taught and practiced around the world. It is extremely difficult – if not impossible – to establish rules for making good art or designing a new object. Instead of generative rules, there are well-established guidelines, styles, and best practices that often only apply to a finished object, or at least a reasonable sketch. Criticizing a work means applying these standards to identify weaknesses and suggest improvements. Some say that it is much less important in art to know how to do something specific than it is to know how to \\"see.\\" Visualization is in many respects similar to design and art: we know a good visualization when we see it (or run a controlled user study on it), but it is impossible to define constructive rules how to design an effective visualization. Critiquing can be a useful tool for teaching, developing better techniques, and more theoretical thinking about visualization.","frontmatter":{"title":"Visualization Criticism","description":"Criticism is a vital part of the practice of design, architecture, and art, and as such is taught and practiced around the world. It is extremely difficult – if not impossible – to establish rules for making good art or designing a new object. Instead of generative rules, there are well-established guidelines, styles, and best practices that often only apply to a finished object, or at least a reasonable sketch. Criticizing a work means applying these standards to identify weaknesses and suggest improvements. Some say that it is much less important in art to know how to do something specific than it is to know how to \\"see.\\" Visualization is in many respects similar to design and art: we know a good visualization when we see it (or run a controlled user study on it), but it is impossible to define constructive rules how to design an effective visualization. Critiquing can be a useful tool for teaching, developing better techniques, and more theoretical thinking about visualization.","featuredImage":"https://media.eagereyes.org/media/2008/VVP-Criticism.png"},"headers":[],"relativePath":"publications/Kosara-CGA-2008.md","filePath":"publications/Kosara-CGA-2008.md"}');
const _sfc_main = { name: "publications/Kosara-CGA-2008.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="visualization-criticism" tabindex="-1">Visualization Criticism <a class="header-anchor" href="#visualization-criticism" aria-label="Permalink to &quot;Visualization Criticism&quot;">​</a></h1><p align="center"><img src="https://media.eagereyes.org/media/2008/VVP-Criticism.png"></p><blockquote><p><em>Criticism is a vital part of the practice of design, architecture, and art, and as such is taught and practiced around the world. It is extremely difficult – if not impossible – to establish rules for making good art or designing a new object. Instead of generative rules, there are well-established guidelines, styles, and best practices that often only apply to a finished object, or at least a reasonable sketch. Criticizing a work means applying these standards to identify weaknesses and suggest improvements. Some say that it is much less important in art to know how to do something specific than it is to know how to &quot;see.&quot; Visualization is in many respects similar to design and art: we know a good visualization when we see it (or run a controlled user study on it), but it is impossible to define constructive rules how to design an effective visualization. Critiquing can be a useful tool for teaching, developing better techniques, and more theoretical thinking about visualization.</em></p></blockquote><p>Robert Kosara, Fritz Drury, Lars Erik Holmquist, and David H. Laidlaw, <a href="https://media.eagereyes.org/papers/2008/Kosara-CGA-2008.pdf" target="_blank">Visualization Criticism</a>, <em>Computer Graphics and Applications (CG&amp;A), Visualization Viewpoints</em>, vol. 28, no. 3, pp. 13–15, 2008. <a href="https://dx.doi.org/10.1109/MCG.2008.63" target="_new">DOI: 10.1109/MCG.2008.63</a></p><div class="language-bibtex"><button title="Copy Code" class="copy"></button><span class="lang">bibtex</span><pre class="shiki material-theme-palenight has-diff"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">@</span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">article</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#FFCB6B" })}">Kosara:CGA:2008</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">year</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">2008</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">title</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Visualization Criticism</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">author</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Robert Kosara and Fritz Drury and Lars Erik Holmquist and David H. Laidlaw</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">venue</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Computer Graphics and Applications (CG&amp;A), Visualization Viewpoints</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">volume</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">28</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">number</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">3</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">pages</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">13–15</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">doi</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">10.1109/MCG.2008.63</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">abstract</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Criticism is a vital part of the practice of design, architecture, and art, and as such is taught and practiced around the world. It is extremely difficult – if not impossible – to establish rules for making good art or designing a new object. Instead of generative rules, there are well-established guidelines, styles, and best practices that often only apply to a finished object, or at least a reasonable sketch. Criticizing a work means applying these standards to identify weaknesses and suggest improvements. Some say that it is much less important in art to know how to do something specific than it is to know how to &quot;see.&quot; Visualization is in many respects similar to design and art: we know a good visualization when we see it (or run a controlled user study on it), but it is impossible to define constructive rules how to design an effective visualization. Critiquing can be a useful tool for teaching, developing better techniques, and more theoretical thinking about visualization.</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("publications/Kosara-CGA-2008.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const KosaraCGA2008 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  KosaraCGA2008 as default
};
