import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Interactive Focus+Context Analysis of Large, Time-Dependent Flow Simulation Data","description":"The visualization of time-dependent simulation data, such as data sets from computational fluid dynamics (CFD) simulation, is still a very challenging task. In this paper, we present a new approach for the interactive visual analysis of flow simulation data, which is especially targeted at the analysis of time-dependent data. This supports the flexible specification and visualization of flow features in an interactive setup of multiple linked views. Special emphasis is put on new mechanisms to capture time-dependent features (i.e. flow features that are inherently dependent on time). We propose the integration of attribute derivation into the process of interactive visual analysis to enable the subsequent user access to otherwise implicit properties of the unsteady data in our interactive feature specification framework. All views of this flow analysis setup are linked, in the sense that the features in focus are consistently emphasized in the visualization (more colorful, less transparent) whereas the rest of the data are only shown as context in reduced style. In addition to introducing our new approach, we also demonstrate its use in the context of several application examples.","frontmatter":{"title":"Interactive Focus+Context Analysis of Large, Time-Dependent Flow Simulation Data","description":"The visualization of time-dependent simulation data, such as data sets from computational fluid dynamics (CFD) simulation, is still a very challenging task. In this paper, we present a new approach for the interactive visual analysis of flow simulation data, which is especially targeted at the analysis of time-dependent data. This supports the flexible specification and visualization of flow features in an interactive setup of multiple linked views. Special emphasis is put on new mechanisms to capture time-dependent features (i.e. flow features that are inherently dependent on time). We propose the integration of attribute derivation into the process of interactive visual analysis to enable the subsequent user access to otherwise implicit properties of the unsteady data in our interactive feature specification framework. All views of this flow analysis setup are linked, in the sense that the features in focus are consistently emphasized in the visualization (more colorful, less transparent) whereas the rest of the data are only shown as context in reduced style. In addition to introducing our new approach, we also demonstrate its use in the context of several application examples."},"headers":[],"relativePath":"publications/Doleisch-Simulation-2006.md","filePath":"publications/Doleisch-Simulation-2006.md"}');
const _sfc_main = { name: "publications/Doleisch-Simulation-2006.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="interactive-focus-context-analysis-of-large-time-dependent-flow-simulation-data" tabindex="-1">Interactive Focus+Context Analysis of Large, Time-Dependent Flow Simulation Data <a class="header-anchor" href="#interactive-focus-context-analysis-of-large-time-dependent-flow-simulation-data" aria-label="Permalink to &quot;Interactive Focus+Context Analysis of Large, Time-Dependent Flow Simulation Data&quot;">​</a></h1><blockquote><p><em>The visualization of time-dependent simulation data, such as data sets from computational fluid dynamics (CFD) simulation, is still a very challenging task. In this paper, we present a new approach for the interactive visual analysis of flow simulation data, which is especially targeted at the analysis of time-dependent data. This supports the flexible specification and visualization of flow features in an interactive setup of multiple linked views. Special emphasis is put on new mechanisms to capture time-dependent features (i.e. flow features that are inherently dependent on time). We propose the integration of attribute derivation into the process of interactive visual analysis to enable the subsequent user access to otherwise implicit properties of the unsteady data in our interactive feature specification framework. All views of this flow analysis setup are linked, in the sense that the features in focus are consistently emphasized in the visualization (more colorful, less transparent) whereas the rest of the data are only shown as context in reduced style. In addition to introducing our new approach, we also demonstrate its use in the context of several application examples.</em></p></blockquote><p>Helmut Doleisch, Helwig Hauser, Martin Gasser, and Robert Kosara, Interactive Focus+Context Analysis of Large, Time-Dependent Flow Simulation Data, <em>Simulation</em>, vol. 82, no. 12, pp. 861–865, 2006.</p><div class="language-bibtex"><button title="Copy Code" class="copy"></button><span class="lang">bibtex</span><pre class="shiki material-theme-palenight"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">@</span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">article</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#FFCB6B" })}">Doleisch:Simulation:2006</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">year</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">2006</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">title</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Interactive Focus+Context Analysis of Large, Time-Dependent Flow Simulation Data</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">author</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Helmut Doleisch and Helwig Hauser and Martin Gasser and Robert Kosara</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">venue</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Simulation</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">volume</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">82</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">number</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">12</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">pages</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">861–865</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">abstract</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">The visualization of time-dependent simulation data, such as data sets from computational fluid dynamics (CFD) simulation, is still a very challenging task. In this paper, we present a new approach for the interactive visual analysis of flow simulation data, which is especially targeted at the analysis of time-dependent data. This supports the flexible specification and visualization of flow features in an interactive setup of multiple linked views. Special emphasis is put on new mechanisms to capture time-dependent features (i.e. flow features that are inherently dependent on time). We propose the integration of attribute derivation into the process of interactive visual analysis to enable the subsequent user access to otherwise implicit properties of the unsteady data in our interactive feature specification framework. All views of this flow analysis setup are linked, in the sense that the features in focus are consistently emphasized in the visualization (more colorful, less transparent) whereas the rest of the data are only shown as context in reduced style. In addition to introducing our new approach, we also demonstrate its use in the context of several application examples.</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("publications/Doleisch-Simulation-2006.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const DoleischSimulation2006 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  DoleischSimulation2006 as default
};
