import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.cc2b3d55.js";
const __pageData = JSON.parse('{"title":"Visualizing Complex Notions of Time","description":"Time plays an important role in medicine. Conditions are not just evaluated at single instants in time, but traced over periods. Medications must be administered within specified temporal limits, and their effects observed with regard to time. When planning treatments, the temporal aspect becomes even more complicated. The planner has to deal with uncertainty and allowable intervals. A visual representation of the information would be helpful, but there are few visualizations of time that are powerful enough. We present a visualization that graphically represents a complex notion of time, and has also been implemented in a program that allows users to directly specify this information. The results of a small user study are reported.","frontmatter":{"title":"Visualizing Complex Notions of Time","description":"Time plays an important role in medicine. Conditions are not just evaluated at single instants in time, but traced over periods. Medications must be administered within specified temporal limits, and their effects observed with regard to time. When planning treatments, the temporal aspect becomes even more complicated. The planner has to deal with uncertainty and allowable intervals. A visual representation of the information would be helpful, but there are few visualizations of time that are powerful enough. We present a visualization that graphically represents a complex notion of time, and has also been implemented in a program that allows users to directly specify this information. The results of a small user study are reported."},"headers":[],"relativePath":"publications/Kosara-MedInfo-2001.md","filePath":"publications/Kosara-MedInfo-2001.md"}');
const _sfc_main = { name: "publications/Kosara-MedInfo-2001.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="visualizing-complex-notions-of-time" tabindex="-1">Visualizing Complex Notions of Time <a class="header-anchor" href="#visualizing-complex-notions-of-time" aria-label="Permalink to &quot;Visualizing Complex Notions of Time&quot;">​</a></h1><blockquote><p><em>Time plays an important role in medicine. Conditions are not just evaluated at single instants in time, but traced over periods. Medications must be administered within specified temporal limits, and their effects observed with regard to time. When planning treatments, the temporal aspect becomes even more complicated. The planner has to deal with uncertainty and allowable intervals. A visual representation of the information would be helpful, but there are few visualizations of time that are powerful enough. We present a visualization that graphically represents a complex notion of time, and has also been implemented in a program that allows users to directly specify this information. The results of a small user study are reported.</em></p></blockquote><p>Robert Kosara and Silvia Miksch, <a href="https://media.eagereyes.org/papers/2001/Kosara-MedInfo-2001.pdf" target="_blank">Visualizing Complex Notions of Time</a>, <em>Proceedings of the Conference on Medical Informatics (MedInfo)</em>, pp. 211–215, 2001.</p><div class="language-bibtex"><button title="Copy Code" class="copy"></button><span class="lang">bibtex</span><pre class="shiki material-theme-palenight"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">@</span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">inproceedings</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#FFCB6B" })}">Kosara:MedInfo:2001</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">year</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#F78C6C" })}">2001</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">title</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Visualizing Complex Notions of Time</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">author</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Robert Kosara and Silvia Miksch</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">venue</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Proceedings of the Conference on Medical Informatics (MedInfo)</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">pages</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">211–215</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">	</span><span style="${ssrRenderStyle({ "color": "#82AAFF" })}">abstract</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">=</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}"> </span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">{</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">Time plays an important role in medicine. Conditions are not just evaluated at single instants in time, but traced over periods. Medications must be administered within specified temporal limits, and their effects observed with regard to time. When planning treatments, the temporal aspect becomes even more complicated. The planner has to deal with uncertainty and allowable intervals. A visual representation of the information would be helpful, but there are few visualizations of time that are powerful enough. We present a visualization that graphically represents a complex notion of time, and has also been implemented in a program that allows users to directly specify this information. The results of a small user study are reported.</span><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span><span style="${ssrRenderStyle({ "color": "#A6ACCD" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#89DDFF" })}">}</span></span></code></pre></div></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("publications/Kosara-MedInfo-2001.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const KosaraMedInfo2001 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  KosaraMedInfo2001 as default
};
